" vim: fdm=marker foldmarker={{{,}}} foldlevel=0

source ~/dotfiles/vim/base.vim

let g:myplugins = {
    \'autocomplete': 'simple/lsp', " pick one
    \'finder': 'ctrlp/fzf/clap', " pick one
    \'web': 1,
    \'lint': 1,
    \'inlinecoderunner': 1,
    \'indentline': 1,
    \}
source ~/dotfiles/vim/plugins.vim

if has("gui_running")
    set lines=40 columns=90

    set guioptions-=m " remove menu bar
    set guioptions-=T " remove toolbar
    set guioptions-=r " remove right scrollbar
    set guioptions-=L " remove left  scrollbar
    set guioptions+=e " use native tab display
endif

syntax enable
