#!/usr/bin/env zsh

# make $PATH a unique array / dedupe
# path and PATH are linked
typeset -aU path

export dotfiles="$HOME/dotfiles"
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"

SHELL_FILES="$HOME/dotfiles/zsh"

# prompt
[ $(command -v starship) ] && eval "$(starship init zsh)"

# init completions
autoload -Uz compinit
compinit
autoload bashcompinit
bashcompinit

#
# plugins
#

# plugins
[[ -f ~/.zsh-snap/znap.zsh ]] ||
    git clone --depth 1 -- \
        https://github.com/marlonrichert/zsh-snap.git ~/.zsh-snap

source ~/.zsh-snap/znap.zsh  # Start Znap

znap source marlonrichert/zsh-autocomplete
znap source zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-syntax-highlighting
znap source Aloxaf/fzf-tab

# plugins settings
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=10'
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

#
# my stuff
#

# History
# Remove older command from the history if a duplicate is to be added.
setopt HIST_IGNORE_ALL_DUPS
setopt autopushd # automatically pushd when cd

# Input/output

# Set editor default keymap to emacs (`-e`) or vi (`-v`)
bindkey -e

# Prompt for spelling correction of commands.
setopt CORRECT

# Customize spelling correction prompt.
# SPROMPT='zsh: correct %F{red}%R%f to %F{green}%r%f [nyae]? '

# Remove path separator from WORDCHARS.
WORDCHARS=${WORDCHARS//[\/]}

alias list_ran_command="zsh -lixc ''"

for file in $SHELL_FILES/plugins/*.sh; do
    source $file
done

FILE="$HOME/dotfiles/_local_/local.sh" && test -f $FILE && source $FILE
