#!/usr/bin/env zsh

# make $PATH a unique array / dedupe
# path and PATH are linked
typeset -aU path

export dotfiles="$HOME/dotfiles"
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"

SHELL_FILES="$HOME/dotfiles/zsh"

#
# theme
#
# needs to load this near the top for instant prompt
source $SHELL_FILES/p10k.zsh
# source $SHELL_FILES/theme.zsh

# init completions
autoload -Uz compinit
compinit
autoload bashcompinit
bashcompinit

#
# plugins
#

# plugin manager
source $SHELL_FILES/zinit.zsh
# source $SHELL_FILES/zim.zsh

# plugins settings
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=10'
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

#
# my stuff
#

# History
# Remove older command from the history if a duplicate is to be added.
setopt HIST_IGNORE_ALL_DUPS

# Input/output
# Set editor default keymap to emacs (`-e`) or vi (`-v`)
bindkey -e
# Prompt for spelling correction of commands.
setopt CORRECT
# Customize spelling correction prompt.
SPROMPT='zsh: correct %F{red}%R%f to %F{green}%r%f [nyae]? '
# Remove path separator from WORDCHARS.
WORDCHARS=${WORDCHARS//[\/]}

alias list_ran_command="zsh -lixc ''"

for file in $SHELL_FILES/plugins/*.sh; do
    source $file
done

FILE="$HOME/dotfiles/_local_/local.sh" && test -f $FILE && source $FILE
